### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by cyclops1982** [berthubert/trifecta#14]
Given that this is such an awesome project, we'd want everybody to run this. Of course, some people have no clue what compiling c++ is, and even worst, have no clue how to just run some software.

In any case, it would be nice to have a docker image that we could just run and give to people.
Bonus points if the CI produces the docker image (no clue if this is possible).

**Comment by berthubert** [comment]
Added support for building static or nearly static libraries, which should make building a docker image very easy.

**Comment by berthubert** [comment]
https://github.com/berthubert/trifecta#distributing-binaries-docker-etc there is an image now!
