### ISSUE TITLE
Add -pthread to CXXFLAGS

### ISSUE THREAD

**Issue by dev-zzo** [berthubert/trifecta#28]
If not done, the build fails with some rather unhelpful messages:

```
dj@MORDOR:~/trifecta$ meson compile -C build
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /home/dj/.local/bin/ninja -C /home/dj/trifecta/build
ninja: Entering directory `/home/dj/trifecta/build'
[18/27] Linking target subprojects/sqlitewriter/demo
FAILED: subprojects/sqlitewriter/demo
c++  -o subprojects/sqlitewriter/demo subprojects/sqlitewriter/demo.p/demo.cc.o subprojects/sqlitewriter/demo.p/sqlwriter.cc.o subprojects/sqlitewriter/demo.p/jsonhelper.cc.o -Wl,--as-needed -Wl,--no-undefined -Wl,--start-group /usr/lib/x86_64-linux-gnu/libsqlite3.so -Wl,--end-group
/usr/bin/ld: subprojects/sqlitewriter/demo.p/demo.cc.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
[24/27] Compiling C++ object testrunner.p/serv.cc.o
ninja: build stopped: subcommand failed.
```

Reconfiguring with the following command fixes the problem:

```
CXXFLAGS="-pthread" /home/dj/.local/bin/meson setup --wipe build
```

**Comment by berthubert** [comment]
Thanks! There is probably a more meson-native solution though. What OS and Meson version are you on?On 26 Dec 2023, at 12:00, Dmitry Janushkevich ***@***.***> wrote:﻿
If not done, the build fails with some rather unhelpful messages:
***@***.***:~/trifecta$ meson compile -C build
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /home/dj/.local/bin/ninja -C /home/dj/trifecta/build
ninja: Entering directory `/home/dj/trifecta/build'
[18/27] Linking target subprojects/sqlitewriter/demo
FAILED: subprojects/sqlitewriter/demo
c++  -o subprojects/sqlitewriter/demo subprojects/sqlitewriter/demo.p/demo.cc.o subprojects/sqlitewriter/demo.p/sqlwriter.cc.o subprojects/sqlitewriter/demo.p/jsonhelper.cc.o -Wl,--as-needed -Wl,--no-undefined -Wl,--start-group /usr/lib/x86_64-linux-gnu/libsqlite3.so -Wl,--end-group
/usr/bin/ld: subprojects/sqlitewriter/demo.p/demo.cc.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
[24/27] Compiling C++ object testrunner.p/serv.cc.o
ninja: build stopped: subcommand failed.

Reconfiguring with the following command fixes the problem:
CXXFLAGS="-pthread" /home/dj/.local/bin/meson setup --wipe build

**Comment by berthubert** [comment]
Hi - if you retry using a fresh checkout you might find this problem has gone away.

**Comment by dev-zzo** [comment]
> What OS and Meson version are you on?

I was using Debian on WSL2. This is likely present on native Debian installs as well.

**Comment by eli-schwartz** [comment]
> Thanks! There is probably a more meson-native solution though. What OS and Meson version are you on?

The meson-native solution was implemented in https://github.com/berthubert/sqlitewrite/pull/2
