### ISSUE TITLE
Current password is not required when changing email address

### ISSUE THREAD

**Issue by wandernauta** [berthubert/trifecta#39]
In the user panel, if you are logged in, changing your password requires providing the current password:

![screenshot](https://github.com/berthubert/trifecta/assets/126832/b2a518b9-7e3d-4bb5-8b04-de155c51f83e)

I assume this is done to make it so that, even in the event that an attacker has managed to steal a session, they cannot create new sessions: they do not know the password, and cannot change the password to one they do know.

However, in the current setup, the attacker could use their stolen session to change the email address (say, to `attacker@example.com`) and then proceed with the "Get sign-in email" flow every time they need a new session. In other words, in this case, being able to change the email address seems to be as useful as being able to change the password.

I would expect the current password to be needed for _both_ the "change password" and "change email" flows (or alternatively: for neither, if this is not something Trifecta worries about).

**Comment by berthubert** [comment]
Good point - will fix this. Thanks!
