### ISSUE TITLE
Email address field in user panel is vulnerable to SMTP injection

### ISSUE THREAD

**Issue by wandernauta** [berthubert/trifecta#40]
Users can change their own email address, but there is no check that the provided input is actually a valid email address, so an "email address" like the following is accepted:

![The form](https://github.com/berthubert/trifecta/assets/126832/2121554c-ea62-4066-9551-1c78eb19b93d)

If this happens, and the user asks for a sign-in email, the canned SMTP snippet is included in the conversation, causing the user-provided email to be sent (shown here in Mailhog):

![Mail shown in Mailhog](https://github.com/berthubert/trifecta/assets/126832/9d8d2bf1-0b11-459b-a510-3932fab8b75e)

In practice, this would allow logged-in Trifecta users to send email to arbitrary destinations (basically, as if they were Trifecta itself).

This is not an issue if all Trifecta users would have been allowed to use the SMTP server anyway, but it looks like this is not the expectation (in the examples, the mail server is listening on `localhost` and SMTP authentication is not used).

**Comment by berthubert** [comment]
thanks - although trifecta is not meant for hostile users, it is still good to fix this.
