### ISSUE TITLE
Blocking-threads design is susceptible to Slowloris-style DoS attacks without nginx

### ISSUE THREAD

**Issue by wandernauta** [berthubert/trifecta#43]
Trifecta, through the cpp-httplib library, uses a fixed-size thread pool (8 threads [by default](https://github.com/yhirose/cpp-httplib/blob/master/httplib.h#L99)) with blocking socket I/O. This means that the app can serve a maximum of 8 connections/requests at once; additional connections are queued. This is probably sufficient in many cases, provided that clients are not too slow.

However, an attacker can [pretend](https://en.wikipedia.org/wiki/Slowloris_(computer_security)) to be very slow, taking multiple seconds to drip-feed a HTTP request. This will keep a thread busy until the 5-second timeout. Opening a bunch of connections, each of which will take 5 seconds to handle when they are eventually handled, effectively denies service to legitimate new connections, without using a lot of bandwidth (~115kb/min on my machine).

To reproduce this locally with the [slowhttptest](https://github.com/shekyan/slowhttptest) tool, try:

```
slowhttptest -c 30 -u http://127.0.0.1:3456/
```

With the `slowloris.pl` script from the Wayback Machine:

```
perl slowloris.pl -dns localhost -port 3456 -timeout 30 -num 60
```

The suggested nginx configuration buffers requests and responses before handing them off to Trifecta, so that configuration should not be affected.

If the expectation is that Trifecta must always be shielded by a proxy that does request buffering and reponse buffering it may be good to document this explicitly. In addition, it would perhaps be neat to extend the Docker Compose example to include something like nginx, so that people don't accidentally deploy it publicly without a proxy.

**Comment by berthubert** [comment]
Without nginx or something similar you also have no TLS, so this does not seem like much of a practical problem. Still thanks for testing though!
