### ISSUE TITLE
Suggested nginx X-Real-IP config assumes nginx is behind another proxy

### ISSUE THREAD

**Issue by wandernauta** [berthubert/trifecta#47]
In README.md, the following nginx configuration is suggested:

```
proxy_set_header X-Real-IP $proxy_protocol_addr;
```

However, `$proxy_protocol_addr` is only set if nginx uses the PROXY protocol, which could be the case if nginx is used behind another proxy like [HAProxy](https://www.haproxy.com/documentation/haproxy-configuration-tutorials/client-ip-preservation/enable-proxy-protocol/) or [AWS ELB](https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-proxy-protocol.html); however, it is not obvious from the README that this is how the configuration is supposed to be used.

If the variable is indeed not set, the X-Real-IP header is never sent to Trifecta, and Trifecta logs all requests as coming from nginx's address (which is technically true, but likely not the intention here).

The following configuration sets the X-Real-IP to the IP address that nginx is talking to, which would better match what I would expect:

```
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```

**Comment by berthubert** [comment]
This has been addressed (somewhat differently) in the documentation
