### ISSUE TITLE
Malicious requests for many overlapping byte ranges of large images risk OOM

### ISSUE THREAD

**Issue by wandernauta** [berthubert/trifecta#49]
Trifecta, through the underlying cpp-httplib library, allows clients to request [a byte range](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests) of the response, using the HTTP `Range` header. For example, the following header requests byte 0 through 5, then byte 10 through 15:

```
% ~ › curl -r 0-5,10-15 http://localhost:8080/trifecta/status
----cpp-httplib-multipart-data-STcIdWlCB5BD4uGr
Content-Type: application/json
Content-Range: bytes 0-5/58

{"admi
----cpp-httplib-multipart-data-STcIdWlCB5BD4uGr
Content-Type: application/json
Content-Range: bytes 10-15/58

alse,"
----cpp-httplib-multipart-data-STcIdWlCB5BD4uGr--
```

Range requests can be a very useful feature, for example when streaming audio: a browser could for example ask first for the first chunk of an MP3 file (probably containing metadata and such), then ask for more chunks as playback progresses.

However, letting the client ask which byte ranges it would like opens up the possibility that an attacker might request some nonsensical ranges: for example a range `0-` (the entire response) and then `0-` (the entire response again) and then `0-` (idem) and so on.

Since responses are built in RAM, the memory that would be required to satisfy this malicious request is the amount of duplicates requested × the size of the original response. This affects Trifecta, because its original responses can be a few megabytes large for high-quality JPEGs.

#### Demonstration

The demonstration requires that some large-ish image is uploaded to Trifecta by some user: I used the full-sized version of [this image](https://commons.wikimedia.org/wiki/File:%D0%9C%D0%BE%D1%80%D0%BE%D0%B7%D0%BD%D0%B8%D0%B9_%D1%80%D0%B0%D0%BD%D0%BE%D0%BA_%D0%BD%D0%B0%D0%B4_%D0%AF%D1%80%D0%B5%D0%BC%D1%87%D0%B5%D1%8E.jpg) from Wikimedia Commons, which is cFv62pX21XI in the example below.

The attacker (which does not need to be the same person) then runs:

```
% ~ › curl -r "$(perl -e 'print "0-," x 2500')0-" http://localhost:8080/trifecta/i/cFv62pX21XI
```

On receiving this request, Trifecta tries to allocate and fill approx. 10 GB of memory, at which point it (or another victim) is killed by the OOM killer – at least on my machine.

This attack is similar to the 2011 "Apache Killer" attack, which is described in more detail [here](https://lwn.net/Articles/456723/). The demonstration uses the nginx configuration from the README, but having nginx proxy the request is not required.

#### Mitigation

A possible workaround would be to suggest that production deployments always strip the `Range` header at the proxy level, for example in nginx:

```
proxy_set_header Range "";
```

This will disappoint, but should not break, legitimate clients that want to use ranges [(ref)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range):

> A server that doesn't support range requests may ignore the Range header and return the whole resource with a 200 status code.

**Comment by berthubert** [comment]
This sounds like a bug for @yhirose/cpp-httplib more? https://github.com/yhirose/cpp-httplib/issues

**Comment by wandernauta** [comment]
Probably that would be the best place for a real fix, but I didn't know whether and how I would phrase it as a bug there – the library claims to do ranges, it does ranges. Having it, say, calculate whether that is really more efficient would perhaps rather be a feature request. I'll leave it up to you.

I've submitted the issue here so that I could share the workaround under 'Mitigation'; that workaround of course only works for Trifecta production instances.

**Comment by berthubert** [comment]
I'll close this for now, it is easy enough to DoS us anyhow now. I've opened an issue over at httlib.

**Comment by berthubert** [comment]
Addressed in https://github.com/yhirose/cpp-httplib/commit/e323374d2abbcfd548c236e767aa2dd7499dcb33
