### ISSUE TITLE
Logging to standard output is not sanitized, leading to possible forged logs or unexpected behavior

### ISSUE THREAD

**Issue by wandernauta** [berthubert/trifecta#50]
Trifecta logs to standard output in a number of instances, primarily in error and exception cases. These log messages can include (binary) data that is taken from the request. However, Trifecta does not sanitize this data, or delineate which parts are controlled by the requester and which parts are not.

This means an determined attacker is able to:

- Put forged entries into the log that are indistinguishable from legitimate entries.
- Hide traces of an attack by using ANSI escapes to change how the log appears in a terminal.
- If an administrator's terminal emulator is [especially vulnerable](https://www.gresearch.com/blog/article/g-research-the-terminal-escapes/): attack their machine through the logs.

The attacker does not need to be authenticated.

#### Demonstration 1

Forging a message could look like this:

```
% ~ › curl -F $'user=fred\nActually never mind, it was fine' http://127.0.0.1:3456/login
```

```
% ~/Code/trifecta › ./buildDir/trifecta
Database is in trifecta.sqlite, canonical URL is http://127.0.0.1:3456/
Admin users: admin 
Will listen on http://127.0.0.1:3456
Wrong user or password for user fred
Actually never mind, it was fine
```

#### Demonstration 2a

All terminal control sequences are passed through unmodified; the following example just turns some text red:

```
% ~ › printf 'POST /join-session/example HTTP/1.0\r\n\r\n' | nc 127.0.0.1 3456
% ~ › printf 'POST /join-session/\e[31mexample%%20but%%20in%%20red\e[0m HTTP/1.0\r\n\r\n' | nc 127.0.0.1 3456
```

![Screenshot](https://github.com/berthubert/trifecta/assets/126832/f9ecf39d-e872-429d-9876-d94947c01972)

#### Demonstration 2b

Finally, we can combine [Chocolate Doom](https://www.chocolate-doom.org/), [catimg](https://github.com/posva/catimg) and libcurl to build a version of id Software's DOOM (1993) that "renders" frames by POSTing them to the `user` field of Trifecta's forgotten-password functionality:

[Recording](https://github.com/berthubert/trifecta/assets/126832/150b5e41-2aa3-42bc-b579-437749d6e592)

Patch available on request (though the game is more fun to play the usual way).

#### Mitigation

Nginx wraps logged user input in double quotes, then [applies](https://nginx.org/en/docs/http/ngx_http_log_module.html#log_format) the following escaping by default:

> Characters “"”, “\”, and other characters with values less than 32 or above 126 are escaped as “\xXX”.

Something similar could work here. It would have to be applied consistently for all printing to stdout, including through the fmt library.

Alternatively, the suggestions for running Trifecta in production could include a suggestion that all stdout logging must be sent to `/dev/null`, and that administrators should only rely on the `log` SQLite table.

**Comment by berthubert** [comment]
The actual logs are in the log table in the database. The printouts to standard output will likely go away.
