### ISSUE TITLE
create link to admin/home/status page 

### ISSUE THREAD

**Issue by roelsroels** [berthubert/trifecta#9]
From UI perspective, would be good to have links to admin/home/status/.. page in the header.

**Comment by cyclops1982** [comment]
We now have a home/admin when you're logged in and are an admin.
#36 is partially related as we might want to introduce a better menu. Something like:
- Home - where you would see a post and/or create update the post (it would have the paste section)
- My Images - to show you your images
- Admin - Users - shows a list of users and allows you to manage those
- Admin - Sessions - shows the sessions
- Admin - images - shows all the images.

@roelvandermade Was that what you had in mind?

Also - what would the status page show?

**Comment by roelsroels** [comment]
The new menu-options and ideas look good to me.
Status page, dunno, maybe sqlite database size, version of trifecta (and if it's the current one available, other #11 )
